[package]
name = "minimal-bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codegen-units = 1
lto = true
opt-level = 'z' # Optimize for size
